# Generated by Django 5.0.6 on 2024-05-19 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=30)),
                ('exchange', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Eod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.DecimalField(decimal_places=0, max_digits=16)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockdata.ticker')),
            ],
        ),
    ]
