# Generated by Django 5.0.6 on 2024-05-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eod',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
